server:
  port: 8082

spring:
  application:
    name: patient-service
  config:
    import: optional:configserver:http://${CONFIG_USER}:${CONFIG_USER_PASSWORD}@localhost:7777
  datasource:
    url: jdbc:postgresql://localhost:5433/patient
    username: patient
    password: Patient0513
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always